#!/bin/sh

SYSTEMCTL=/bin/systemctl

case "$1" in
    battery)
        echo 'Running on battery. Making sure to remove the inhibit lock'
        $SYSTEMCTL stop no-suspend-on-lid-close.service
        ;;

    ac)
        echo 'Running on AC. Making sure to add the inhibit lock'
        $SYSTEMCTL start no-suspend-on-lid-close.service
        ;;

    -h|--help|help)
        echo "Usage: $(basename $0) [battery|ac]"
        exit 1
        ;;

    *)
        echo 'Automatically detecting power source...'

        if cat /sys/class/power_supply/AC/online | grep 0 > /dev/null 2>&1
        then
            $0 battery
        else
            $0 ac
        fi

        exit $?
        ;;
esac

exit 0
